# Generated by Django 6.0.3 on 2026-03-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('keyword', 'content_item')},
        ),
    ]
